<?php echo $this->render("header.phtml") ?>

<script>
        dojo.require("dijit.form.FilteringSelect");
       dojo.require("dijit.form.Button");
</script>

<h2><?php echo $this->escape($this->title); ?></h2>


<form action="<?php echo $this->baseUrl ?>/admin/convenio/listtermino" method="get">
<table>

<tr>
	
<td><label for="argumentInput">Ano: </label>
   <select dojoType="dijit.form.FilteringSelect" name="ano" >
   		<option value="">-----------------------------------</option>
<?php $i = 0 ?>
<?php while ($i < count($this->anos)): ?>
	<?php foreach ($this->anos[$i] as $anos): ?>
                <option value="<?php echo $anos; ?>"><?php echo $anos; ?></option>
     <?php endforeach; ?>
     <?php $i++; ?>
<?php endwhile; ?>     
      </select>
</td>
<td>   
<label for="argumentInput">Mês: </label>
   <select dojoType="dijit.form.FilteringSelect" name="mes"  >
                <option value="" >-----------------------------------</option>
                <option value="01" >Janeiro</option>
                <option value="02" >Fevereiro</option>
                <option value="03" >Março</option>
                <option value="04" >Abril</option>
                <option value="05" >Maio</option>
                <option value="06" >Junho</option>
                <option value="07" >Julho</option>
                <option value="08" >Agosto</option>
                <option value="09" >Setembro</option>
                <option value="10" >Outubro</option>
                <option value="11" >Novembro</option>
                <option value="12" >Dezembro</option>
   </select>
</td>   
</tr>  
 
</table><br>  


   <input name="button" type="submit" value="Buscar" dojoType="dijit.form.Button" label="Buscar" />
</form>
<br /><br />
<div>

<?php if(!$this->conveniosList): ?>
	
<?php else : ?>
	<?php if(count($this->conveniosList) == 0) : ?>
	Não há convênios que terminem no mês e ano selecionados.
	
	<?php else : ?>
	<table border="1" width="580px" class="tabela">
		<thead>
			<th width="40%">Nome</th>
			<th>Registro</th>
			<th>Data Início</th>
			<th>Data Final</th>
		</thead>
		<tbody>
		<?php foreach ($this->conveniosList as $convenio) : ?>
			<tr>
				<td><?php echo $convenio->nome ?></td>
				<td><?php echo $convenio->registro ?></td>
				<td><?php $ano = strtok($convenio->dataInicio,"-");
												  $mes = strtok("-");
												  $dia = strtok("-");	
												  echo $dia."-".$mes."-".$ano ?></td>
				<td><?php $ano = strtok($convenio->dataFinal,"-");
												  $mes = strtok("-");
												  $dia = strtok("-");	
												  echo $dia."-".$mes."-".$ano ?></td>
			</tr>
		<?php endforeach; ?>	
		</tbody>
	</table>	
	<?php endif; ?>
<?php endif; ?>


</div>
	

<?php echo $this->render("footer.phtml") ?>