<?php echo $this->render('header.phtml'); ?>
<h2><?php echo $this->escape($this->title); ?></h2>
<div id="listaEventos">

<?php if(count($this->eventos) == 0) : ?>
Não existem eventos salvos.

<?php else : ?>
<table border="1" width="580px" class="tabela">
	<thead>
		<th width="40%"></th>
		<th>Nome</th>
	</thead>
	<tbody>
<?php if(count($this->eventos) == 0) echo 'Não existem eventos salvos.' ?>
<?php foreach ($this->eventos as $evento) : ?>
	<tr>
		<td align="center">
		<?php if($evento->idAreaTematica) : ?>
			<form action="<?php echo $this->baseUrl ?>/evento/imprimirFormulario" method="get" style="display: inline">
				<input type="hidden" name="id" value="<?php echo $evento->id?>" />
				<button type="submit" class="printButton">Imprimir</button>
			</form>
		<?php endif; ?>
		<!-- Retirar para incluir relatório final
		<form action="<?php echo $this->baseUrl ?>/evento/relatorioFinal" method="get" style="display: inline;">
			<input type="hidden" name="id" value="<?php echo $evento->id?>" />
			<button type="submit" class="reportButton">Relatório Final</button>
		</form> -->
		<td><?php echo $evento->titulo?></td>
	</tr>
<?php endforeach; ?>
	</tbody>
</table>

<?php endif; ?>
	
</div>
<?php echo $this->render('footer.phtml'); ?>