<?php echo $this->render('header.phtml'); ?>
<?php echo $this->render('menu-curso.phtml'); ?>

<script>
       dojo.require("dijit.form.Textarea");
       dojo.require("dijit.form.NumberSpinner");
</script>

<h2><?php echo $this->escape($this->title); ?></h2>

<?php if($this->errors) : ?>
<div id="errors">
	<?php foreach ($this->errors as $error) echo $error . "<br />" ?>
</div><br />
<?php endif; ?>

<form id="formDescricao" action="<?php echo $this->baseUrl ?>/curso/descricao" method="post">
	<input name="id" type="hidden" value="<?php echo $this->curso->id ?>" />
	
<!-- div id="helpFundamento" class="help">
<p>Descrição referenciada que demonstre claramente que o curso está inserido dentro da proposta de indissociabilidade dos
parâmetros de Ensino, Pesquisa, Extensão.</p>
</div-->

<div>
	<label for="descricao">Descrição:</label><br />
	<textarea name="descricao" dojoType="dijit.form.Textarea" style="width:575px">
    	<?php echo $this->escape($this->curso->descricao) ?>
    </textarea>
</div>
<br />

<div>
	<label for="expectativaPublico">Expectativa de público:</label>
	<input name="expectativaPublico" dojoType="dijit.form.NumberSpinner"
                value="<?php echo $this->curso->expectativaPublico ?>"
                constraints="{min:0,places:0}"
                maxlength="20">pessoas.
</div><br />


<div>
	<label for="publicoAlvo">Público alvo:</label>
	<!-- img src="<?php echo $this->baseUrl ?>/public/images/question-mark-icon.gif" title="Ajuda" onmouseover="setVisible('helpFundamento', true)"  onmouseout="javascript:setVisible('helpFundamento', false)"/--><br />
	<textarea name="publicoAlvo" dojoType="dijit.form.Textarea" style="width:575px">
    	<?php echo $this->escape($this->curso->publicoAlvo) ?>
    </textarea>
</div>
<br />
<div id="helpResumo" class="help">
<p>O resumo deve ser sucinto, contendo informações básicas sobre os objetivos, a metodologia e
	    o público alvo que permitam uma melhor visualização do curso , além do local de realização, 
	    horários de atendimento ou de execução do curso. Este  resumo será  divulgado na  página da 
	    Proexc  e, portanto, o texto deverá ser revisado e é de responsabilidade do coordenador. 
	    Poderá conter e-mail para contato ou endereço de site. 
</p>
</div>
<div>
	<div class="moreHelp">
		<font color="red">O resumo deve ser sucinto, contendo informações básicas sobre os objetivos, a metodologia e
	    o público alvo que permitam uma melhor visualização do curso , além do local de realização, 
	    horários de atendimento ou de execução do curso. Este  resumo será  divulgado na  página da 
	    Proexc  e, portanto, o texto deverá ser revisado e é de responsabilidade do coordenador. 
	    Poderá conter e-mail para contato ou endereço de site.</font>
	</div>
	<br />
	
	<label for="resumo">Resumo (Informações para o público externo):</label>
	<img src="<?php echo $this->baseUrl ?>/public/images/question-mark-icon.gif" title="Ajuda" 
	onmouseover="setVisible('helpResumo', true)"  onmouseout="javascript:setVisible('helpResumo', false)"/>	
	
	
	<textarea name="resumo" dojoType="dijit.form.Textarea" style="width:575px">
	<?php if($this->curso->resumo){echo $this->escape($this->curso->resumo);} ?>
	</textarea>
	
	<label for="local">Local para informações:</label>
    <textarea name="local" dojoType="dijit.form.Textarea" style="width:575px"  >
	<?php if($this->curso->localInformacoes){echo $this->escape($this->curso->localInformacoes);} ?> 
    </textarea> 
    
    <label for="local">E-mail para informações:</label>
    <textarea name="email" dojoType="dijit.form.Textarea" style="width:575px" >
	<?php if($this->curso->emailInformacoes){echo $this->escape($this->curso->emailInformacoes);} ?> 
    </textarea>
    
    <label for="telefone">Telefone para informações:</label>
    <textarea name="telefone" dojoType="dijit.form.Textarea" style="width:575px"  >
	<?php if($this->curso->telInformacoes){echo $this->escape($this->curso->telInformacoes);} ?> 
    </textarea>
    
</div><br />

<div>	
	<input name="button" type="submit" value="Salvar" />
	<input name="button" type="submit" value="Proximo" />
</div>
</form>
<?php echo $this->render('footer.phtml'); ?>