<?php echo $this->render('header.phtml'); ?>
<h2><?php echo $this->escape($this->title); ?></h2>
<?php if ($this->tecnico) :?>
<form action="<?php echo $this->baseUrl ?>/projeto/delColaboradorTecnico" method="post">
	<input type="hidden" name="id" value="<?php echo $this->idProjeto?>" />
	<p>Tem certeza que deseja apagar o técnico 
		'<?php echo $this->escape($this->tecnico->nome); ?>'?</p>
	<div>
		<input type="hidden" name="idTecnico" value="<?php echo $this->tecnico->id; ?>" />
		<input type="submit" name="del" value="Yes" />
		<input type="submit" name="del" value="No" />
	</div>
</form>
<?php else: ?>
<p>Técnico não encontrado.</p>
<?php echo $this->error ?>
<?php endif;?>
<?php echo $this->render('footer.phtml'); ?>
