<?php echo $this->render('header.phtml'); ?>
<?php echo $this->render('menu-projeto.phtml'); ?>

<script>
       dojo.require("dijit.form.TextBox");
       dojo.require("dijit.form.FilteringSelect");
       dojo.require("dijit.form.Button");
</script>

<h2><?php echo $this->escape($this->title); ?></h2>

<div class="help" id="helpCoordenadoresTecnicos">
<p>O coordenador técnico, de competência técnica reconhecida, atua no projeto sob a orientação e tutela do coordenador geral,
podendo orientar tecnicamente os bolsistas. Neste caso, não existe, para a candidatura ao cargo, a necessidade de ser professor
da UFJF.</p>
</div>

<div class="help" id="helpViceCoordenador">
<p>O vice coordenador, <u>docente da UFJF cadastrado no sistema PROEXC</u>, trabalha conjuntamente com o coordenador, podendo assumir temporariamente ou
definitivamente o projeto.</p> Caso o Vice-Coordenador não apareça na lista de Vice-Coordenadores possíveis é necessário que o mesmo se cadastre no sistema PROEXC.
</div>

<div class="help" id="helpColaboradoresDocentes">
<p>Docente da UFJF que irá assumir o papel de colaborador no projeto.</p>
</div>

<div class="help" id="helpColaboradoresTecnicos">
<p>Técnico-administrativo da UFJF que irá assumir o papel de colaborador no projeto.</p>
</div>

<div class="help" id="helpColaboradoresExternos">
<p>Qualquer pessoa, da UFJF ou não, que irá assumir o papel de colaborador no projeto.</p>
</div>

<form id="myForm" action="<?php echo $this->baseUrl ?>/projeto/equipe" method="post">
	<input name="id" type="hidden" value="<?php echo $this->projeto->id ?>" />
	
<img class="icon" src="<?php echo $this->baseUrl ?>/public/images/question-mark-icon.gif" title="Ajuda" onmouseover="setVisible('helpViceCoordenador', true)"  onmouseout="javascript:setVisible('helpViceCoordenador', false)"/>
<div>	
	<label for="idViceCoordenador">Vice Coordenador:</label>
	<select name="idViceCoordenador" dojoType="dijit.form.FilteringSelect">
	<option value="0">Nenhum</option>
	<?php foreach($this->viceCoordenadores as $viceCoordenador) : ?>
		<option value="<?php echo $viceCoordenador->id ?>"
		<?php if($this->projeto->idViceCoordenador == $viceCoordenador->id) : ?>
			selected="selected"<?php endif; ?>
			><?php echo $viceCoordenador->nome ?> - <?php echo $viceCoordenador->findParentDepartamento()->nome ?></option>			
	<?php endforeach; ?>
	</select>
</div><br />

<img class="icon" src="<?php echo $this->baseUrl ?>/public/images/question-mark-icon.gif" title="Ajuda" onmouseover="setVisible('helpCoordenadoresTecnicos', true)"  onmouseout="javascript:setVisible('helpCoordenadoresTecnicos', false)"/>
<div>
	<fieldset>
	<legend>
		Coordenadores Técnicos
	</legend>
	<span id="coordenadorTecnico">
		<a href="<?php echo $this->baseUrl?>/projeto/addCoordenadorTecnico/id/<?php echo $this->projeto->id?>">Adicionar</a>
		<br />
		<?php if($this->coordenadoresTecnicos) foreach($this->coordenadoresTecnicos as $coordenadorTecnico) : ?>
			<?php echo $coordenadorTecnico->nome ?> 
			<a href="<?php echo $this->baseUrl?>/projeto/editCoordenadorTecnico/id/<?php echo $this->projeto->id?>/idTecnico/<?php echo $coordenadorTecnico->id?>">Editar</a>
			<a href="<?php echo $this->baseUrl?>/projeto/delCoordenadorTecnico/id/<?php echo $this->projeto->id?>/idTecnico/<?php echo $coordenadorTecnico->id?>">Apagar</a>
			<br />
		<?php endforeach;?>
	</span>
	</fieldset>
</div>

<img class="icon" src="<?php echo $this->baseUrl ?>/public/images/question-mark-icon.gif" title="Ajuda" onmouseover="setVisible('helpColaboradoresDocentes', true)"  onmouseout="javascript:setVisible('helpColaboradoresDocentes', false)"/>
<div>
	<fieldset>
	<legend>Colaboradores Docentes</legend>
	<span id="colaboradorDocente">
		<a href="<?php echo $this->baseUrl?>/projeto/addColaboradorDocente/id/<?php echo $this->projeto->id?>">Adicionar</a>
		<br />
		<?php if($this->colaboradoresDocentes) foreach($this->colaboradoresDocentes as $colaboradorDocente) : ?>
			<?php echo $colaboradorDocente->nome ?> 
			<a href="<?php echo $this->baseUrl?>/projeto/editColaboradorDocente/id/<?php echo $this->projeto->id?>/idColaboradorDocente/<?php echo $colaboradorDocente->id?>">Editar</a>
			<a href="<?php echo $this->baseUrl?>/projeto/delColaboradorDocente/id/<?php echo $this->projeto->id?>/idColaboradorDocente/<?php echo $colaboradorDocente->id?>">Apagar</a>
			<br />
		<?php endforeach;?>
	</span>
	</fieldset>
</div>

<img class="icon" src="<?php echo $this->baseUrl ?>/public/images/question-mark-icon.gif" title="Ajuda" onmouseover="setVisible('helpColaboradoresTecnicos', true)"  onmouseout="javascript:setVisible('helpColaboradoresTecnicos', false)"/>
<div>
	<fieldset>
	<legend>Colaboradores Técnicos</legend>
	<span id="colaboradorTecnico">
		<a href="<?php echo $this->baseUrl?>/projeto/addColaboradorTecnico/id/<?php echo $this->projeto->id?>">Adicionar</a>
		<br />
		<?php if($this->colaboradoresTecnicos) foreach($this->colaboradoresTecnicos as $colaboradorTecnico) : ?>
			<?php echo $colaboradorTecnico->nome ?> 
			<a href="<?php echo $this->baseUrl?>/projeto/editColaboradorTecnico/id/<?php echo $this->projeto->id?>/idTecnico/<?php echo $colaboradorTecnico->id?>">Editar</a>
			<a href="<?php echo $this->baseUrl?>/projeto/delColaboradorTecnico/id/<?php echo $this->projeto->id?>/idTecnico/<?php echo $colaboradorTecnico->id?>">Apagar</a>
			<br />
		<?php endforeach;?>
	</span>
	</fieldset>
</div>

<img class="icon" src="<?php echo $this->baseUrl ?>/public/images/question-mark-icon.gif" title="Ajuda" onmouseover="setVisible('helpColaboradoresExternos', true)"  onmouseout="javascript:setVisible('helpColaboradoresExternos', false)"/>
<div>
	<fieldset>
	<legend>Colaboradores Externos</legend>
	<span id="colaboradorExterno">
		<a href="<?php echo $this->baseUrl?>/projeto/addColaboradorExterno/id/<?php echo $this->projeto->id?>">Adicionar</a>
		<br />
		<?php if($this->colaboradoresExternos) foreach($this->colaboradoresExternos as $colaboradorExterno) : ?>
			<?php echo $colaboradorExterno->nome ?> 
			<a href="<?php echo $this->baseUrl?>/projeto/editColaboradorExterno/id/<?php echo $this->projeto->id?>/idColaboradorExterno/<?php echo $colaboradorExterno->id?>">Editar</a>
			<a href="<?php echo $this->baseUrl?>/projeto/delColaboradorExterno/id/<?php echo $this->projeto->id?>/idColaboradorExterno/<?php echo $colaboradorExterno->id?>">Apagar</a>
			<br />
		<?php endforeach;?>
	</span>
	</fieldset>
</div>
<div>	
	<input name="button" type="submit" value="Salvar" />
	<input name="button" type="submit" value="Proximo" />
</div>
</form>

<?php echo $this->render('footer.phtml'); ?>