<?php echo $this->render('header.phtml'); ?>

<h2><?php echo $this->escape($this->title); ?></h2>

<?php echo $this->render('simpleForm/_form.phtml'); ?>

<?php if(count($this->modelList) == 0) : ?>
	<p>Não há nenhum dado cadastrado.</p>
<?php else : ?>
<table border="1" width="300px" class="tabela">
	<thead>
		<th>Nome</th>
		<th>Ação</th>
	</thead>
	<tbody>
<?php foreach ($this->modelList as $model) : ?>
	<tr>
		<td><a href="<?php echo $this->baseUrl ?>/admin/<?php echo $this->modelName ?>/edit/id/<?php echo $model->id?>"><?php echo $model->nome ?></a></td>
		<td><a href="<?php echo $this->baseUrl ?>/admin/<?php echo $this->modelName ?>/delete/id/<?php echo $model->id?>">deletar</a></td>
	</tr>
<?php endforeach; ?>
	</tbody>
</table>	
<?php endif; ?>

<?php echo $this->render('footer.phtml'); ?>