<script>
       dojo.require("dijit.form.TextBox");
       dojo.require("dijit.form.Button");
</script>

<?php if($this->errors) : ?>
<div id="errors">
	<?php foreach ($this->errors as $error) echo $error . "<br />" ?>
</div>
<?php endif; ?>

<form method="post" style="width: 600px">
	
<p>
	<label for="nome">Nome:</label>
	<input type="text" id="nome" name="nome" maxlength="255" dojoType="dijit.form.TextBox" required="true"
		   value="<?php echo $this->escape($this->usuario->nome) ?>" />
</p>
<p>
	<label for="login">Login:</label>
	<input type="text" name="login" id="login" maxlength="20" dojoType="dijit.form.TextBox" required="true"
		   value="<?php echo $this->escape($this->usuario->login) ?>" />
</p>
<p>
	<label for="role">Role:</label>
	<select name="role" id="role">
		<option value="manager">gerente</option>
	</select>
</p>
<p>
	<label for="pwd">Senha:</label>
	<input type="password" name="pwd" id="pwd" maxlength="20" dojoType="dijit.form.TextBox" required="true" />
</p>
<p>
	<label for="pwd2">Repita a senha:</label>
	<input type="password" name="pwd2" id="pwd2" maxlength="20" dojoType="dijit.form.TextBox" required="true" />
</p>

<p>	
	<input name="button" type="submit" value="Salvar" dojoType="dijit.form.Button" label="Salvar" />
</p>
</form>