<?php echo $this->render('header.phtml'); ?>

<script>
	dojo.require("dijit.form.TextBox");
	dojo.require("dijit.form.Button");
</script>

<h2><?php echo $this->escape($this->title); ?></h2>

<?php if($this->errors) : ?>
<div id="errors">
	<?php foreach ($this->errors as $error) echo $error . "<br />" ?>
</div>
<?php endif; ?>

<form action="<?php echo $this->baseUrl ?>/evento/add" method="post">
<label for="titulo">Título:</label>
<input type="text" name="titulo" dojoType="dijit.form.TextBox" />
<input type="submit" value="Criar" label="Criar" dojoType="dijit.form.Button" />
</form>
<?php echo $this->render('footer.phtml'); ?>