<?php echo $this->render('header_no_menu.phtml'); ?>
<h2><?php echo $this->escape($this->title); ?></h2>

<?php if(!empty($this->message)) :?>
<div id="message">
<?php echo $this->escape($this->message);?>
</div>
<?php endif; ?>

<form name="form1" action="login" method="post">
<div>
    <label for="username">Username</label>
    <input type="text" name="username"/>
</div>
<div>
    <label for="password">Password</label>
    <input type="password" name="password"/>
</div>
<div id="formbutton">
<input type="submit" name="login" value="Login" />
</div>
</form>

<?php echo $this->render('footer.phtml'); ?>