<?php echo $this->render('header.phtml'); ?>

<script>
	dojo.require("dijit.form.TextBox");
    dojo.require("dijit.form.Button");
    dojo.require("dijit.TitlePane");
    dojo.require("dijit.Editor");
      
    function editarAgenda(idAgenda) {
    	location.href = "agenda/edit/id/" + idAgenda;
    }
</script>

<h2>Agenda</h2>

<form>
<p><label for="argumentInput">Nome: </label>
   <input type="text" name="s" id="argumentInput" maxlength="255" dojoType="dijit.form.TextBox" />
   <input name="button" type="submit" value="Buscar" dojoType="dijit.form.Button" label="Buscar" />
</p>
</form>

<?php if($this->agendaList) : ?>
	<?php if(count($this->agendaList) == 0) : ?>
	<p>A busca não retornou resultados.</p>
	<?php else : ?>
	<?php foreach ($this->agendaList as $agenda) : ?>
		<div dojoType="dijit.TitlePane" title="<?php echo new Zend_Date($agenda->timestamp) . " - <b>" . $agenda->titulo . "</b>"?>" open="false">
			<?php echo $agenda->descricao ?>
		<button dojoType="dijit.form.Button" onclick="editarAgenda(<?php echo $agenda->id ?>)">Editar</button>
		</div>
	<?php endforeach; ?>
	<?php endif; ?>
<?php endif; ?>

<?php echo $this->render('footer.phtml'); ?>