<?php echo $this->render('header.phtml'); ?>

<h2><?php echo $this->escape($this->title); ?></h2>

<script type="text/javascript">
<!--
       dojo.require("dijit.form.Button");
//-->
</script>

<?php echo $this->render('departamento/_form.phtml'); ?>

<p>	
	<input name="button" type="submit" value="Salvar" dojoType="dijit.form.Button" label="Salvar">
</p>
</form>

<?php echo $this->render('footer.phtml'); ?>