<h2>Evento: <?php echo $this->evento->titulo ?></h2>

<div id="projetoMenu">
	<ul>
		<li><a href="<?php echo $this->baseUrl?>/evento/geral/id/<?php echo $this->evento->id ?>">Geral</a></li>
		<li><a href="<?php echo $this->baseUrl?>/evento/descricao/id/<?php echo $this->evento->id ?>">Descrição</a></li>
		<li><a href="<?php echo $this->baseUrl?>/evento/recursos/id/<?php echo $this->evento->id ?>">Recursos</a></li>
	</ul>
</div>