<h2>Curso: <?php echo $this->curso->titulo ?></h2>

<div id="projetoMenu">
	<ul>
		<li><a href="<?php echo $this->baseUrl?>/curso/geral/id/<?php echo $this->curso->id ?>">Geral</a></li>
		<li><a href="<?php echo $this->baseUrl?>/curso/equipe/id/<?php echo $this->curso->id ?>">Equipe</a></li>
		<li><a href="<?php echo $this->baseUrl?>/curso/descricao/id/<?php echo $this->curso->id ?>">Descrição</a></li>
		<li><a href="<?php echo $this->baseUrl?>/curso/recursos/id/<?php echo $this->curso->id ?>">Recursos</a></li>
	</ul>
</div>