<?php echo $this->render('header.phtml'); ?>

<script>
       dojo.require("dijit.form.TextBox");
       dojo.require("dijit.form.Button");
</script>

<h2><?php echo $this->escape($this->title); ?></h2>

<form>
<p><label for="argumentInput">Nome: </label>
   <input type="text" name="s" id="argumentInput" maxlength="255" dojoType="dijit.form.TextBox" />
   <input name="button" type="submit" value="Buscar" dojoType="dijit.form.Button" label="Buscar" />
</p>
</form>

<?php if($this->usuarioList) : ?>
	<?php if(count($this->usuarioList) == 0) : ?>
	<p>A busca não retornou resultados.</p>
	<?php else : ?>
	<table border="1" width="300px" class="tabela">
		<thead>
			<th>Nome</th>
			<th>Login</th>
			<th>Ação</th>
		</thead>
		<tbody>
		<?php foreach ($this->usuarioList as $usuario) : ?>
			<tr>
				<td><a href="<?php echo $this->baseUrl ?>/admin/usuario/edit/login/<?php echo $usuario->login?>"><?php echo $usuario->nome ?></a></td>
				<td><a href="<?php echo $this->baseUrl ?>/admin/usuario/edit/login/<?php echo $usuario->login?>"><?php echo $usuario->login ?></a></td>
				<td><a href="<?php echo $this->baseUrl ?>/admin/usuario/delete/login/<?php echo $usuario->login?>">deletar</a></td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>	
	<?php endif; ?>
<?php endif; ?>

<?php echo $this->render('footer.phtml'); ?>